apiVersion: v1
kind: Service
metadata:
  name: video-processing-service
spec:
  selector:
    app: video-processing-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
